(("anything" "git://github.com/haxney/anything.git")
 ("anything-config" "git://github.com/haxney/anything-config.git")
 ("anything-contrib" "git://github.com/haxney/anything-contrib.git")
 ("bm" "git://github.com/haxney/bm.git")
 ("package" "git://github.com/haxney/package.git")
 ("traverselisp" "git://github.com/haxney/traverselisp.git")
 ("auto-install" "git://github.com/haxney/auto-install.git")
 ("undo-tree" "git://github.com/haxney/undo-tree.git")
 ("linkd" "git://github.com/haxney/linkd.git")
 ("unbound" "git://github.com/haxney/unbound.git")
 ("graphviz-dot-mode" "git://github.com/haxney/graphviz-dot-mode.git")
 ("quack" "git://github.com/haxney/quack.git")
 ("mysql" "git://github.com/haxney/mysql.git")
 ("smex" "git://github.com/haxney/smex.git")
 ("notify" "git://github.com/haxney/notify.git")
 )
