(("anything" "git://github.com/haxney/anything.git")
 ("anything-config" "git://github.com/haxney/anything-config.git")
 ("anything-contrib" "git://github.com/haxney/anything-contrib.git")
 ("bm" "git://github.com/haxney/bm.git")
 ("package" "git://github.com/haxney/package.git")
 ("traverselisp" "git://github.com/haxney/traverselisp.git")
 ("auto-install" "git://github.com/haxney/auto-install.git")
 )
